# 'image' commence au début de la ligne
image:
  file: .gitpod.Dockerfile

# 'tasks' commence au début de la ligne
tasks:
  - name: Dépendances et Services
    init: |
      echo "Pré-téléchargement de l'image Cosmos DB..."
      docker pull mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:vnext-preview
      echo "Installation des dépendances du projet..."
      npm install
    command: |
      echo "Démarrage de l'émulateur Cosmos DB en arrière-plan..."
      docker compose up -d
      echo "Attente du démarrage de l'émulateur (15s)..."
      sleep 15
      echo "Exportation et installation du certificat de l'émulateur..."
      openssl s_client -connect localhost:8081 </dev/null | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' > cosmos_emulator.cert
      sudo cp cosmos_emulator.cert /usr/local/share/ca-certificates/
      sudo update-ca-certificates
      echo "Certificat installé avec succès."
      npm start

# 'ports' commence aussi au début de la ligne
ports:
  # Chaque port (commençant par '-') est indenté de deux espaces
  - [cite_start]port: 3000 # [cite: 127]
    onOpen: open-preview
  - port: 8081
    onOpen: ignore
  - port: 1234
    onOpen: open-preview
    name: Cosmos-Explorer