# Indique à Gitpod d'utiliser notre image Docker personnalisée [cite: 108, 109]
image:
  file: .gitpod.Dockerfile

tasks:
  - name: Dépendances et Services
    # 'init' : Commandes exécutées pendant la pré-construction (prebuild) pour un démarrage rapide [cite: 89, 94]
    init: |
      echo "Pré-téléchargement de l'image Cosmos DB..."
      docker pull mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:vnext-preview [cite: 91, 92, 113]
      echo "Installation des dépendances du projet..."
      # Remplacez par la commande de votre projet (ex: pip install -r requirements.txt, dotnet restore)
      npm install [cite: 93, 114]
    # 'command' : Commandes exécutées au démarrage de l'espace de travail [cite: 96]
    command: |
      echo "Démarrage de l'émulateur Cosmos DB en arrière-plan..."
      docker compose up -d [cite: 97, 116]
      echo "Attente du démarrage de l'émulateur (15s)..."
      sleep 15 [cite: 118]

      # --- Section critique : Installation du certificat SSL de l'émulateur --- [cite: 167, 170]
      echo "Exportation et installation du certificat de l'émulateur..."
      [cite_start]openssl s_client -connect localhost:8081 </dev/null | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' > cosmos_emulator.cert [cite: 120, 121, 177]
      [cite_start]sudo cp cosmos_emulator.cert /usr/local/share/ca-certificates/ [cite: 122, 178]
      [cite_start]sudo update-ca-certificates [cite: 123, 179]
      [cite_start]echo "Certificat installé avec succès." [cite: 124, 180]

      # Démarrage de votre application
      [cite_start]npm start [cite: 100, 125]

# Gère la manière dont Gitpod expose les ports des services [cite: 102]
ports:
  # Port de votre application (à adapter si besoin)
  - [cite_start]port: 3000 [cite: 127]
    [cite_start]onOpen: open-preview [cite: 128]
  # Port de l'API de l'émulateur, pas besoin de l'ouvrir
  - [cite_start]port: 8081 [cite: 129]
    [cite_start]onOpen: ignore [cite: 130]
  # Port de l'explorateur de données, on l'ouvre pour voir nos données
  - [cite_start]port: 1234 [cite: 131]
    [cite_start]onOpen: open-preview [cite: 132]
    [cite_start]name: Cosmos-Explorer [cite: 133]